import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ja">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <main className="min-w-screen-md mx-auto p4">
          <header style={{ backgroundColor: "#09f", color: "#FFF" }}>
            <h1>Next.jsサンプル</h1>
            <nav>
              <a href="/">Home</a> | <a href="/about">About</a>
            </nav>
          </header>
          {children}
          <footer>
            <p style={{ background: "#09f", padding: "10px" }}>
              2025 Next.jsサンプルa
            </p>
          </footer>
        </main>
      </body>
    </html>
  );
}
